language: generic
addons:
  apt:
    packages:
      - oracle-java8-set-default
install:
  - wget http://update.rascal-mpl.org/console/rascal-shell-stable.jar
  - /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx1G -Xss32m -jar rascal-shell-stable.jar Main.rsc
notifications:
  email:
    on_success: never
    on_failure: never
